version: "3.8"

services:
  database:
    container_name: mongo-db
    image: mongo:5.0
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
    ports:
      - '27017:27017'
    volumes: 
      - mongo-data:/data/db
  mongo-express:
    container_name: mongo-express
    image: mongo-express:0.54
    depends_on:
      - database
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo-db
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_ROOT_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_ROOT_PASSWORD}
      ME_CONFIG_MONGODB_ENABLE_ADMIN: true
      ME_CONFIG_BASICAUTH_USERNAME: ${ME_USERNAME}
      ME_CONFIG_BASICAUTH_PASSWORD: ${ME_PASSWORD}
    ports:
      - '6082:8081'
    volumes: 
      - me-data:/data/db 

volumes:
  mongo-data:
  me-data:
